### ISSUE TITLE
Cache results

### ISSUE THREAD

**Issue by fatso83** [hut8/github-contributions#16]
Compared to the enormous amount of data you are working with I would assume that the (presumably) little traffic that's hitting you would be manageable to cache for each user (to some extent).

For interested developers that would poll your site regularly, this should lower the load quite a bit.

**Comment by hut8** [comment]
Mongo seems to cache it for me.

If you request this:
http://githubcontributions.io/user/fatso83

or:
http://githubcontributions.io/user/fatso83/events

Then request it again, isn't it instant the second time?

**Comment by hut8** [comment]
Also if you have an idea of a more intelligent way to do this, I'm all ears. I was actually thinking of making a `.json.bz2` for each user and doing away with any sort of real database. Even though this seems insane, some early results were promising, except that compiling those files would take months initially (benchmarked with a magnetic-drive VPS and ext4), and appending to each would require unzipping each so that it would have a chance to re-compress it efficiently.

**Comment by fatso83** [comment]
I have no idea why I did not respond to this, but yeah, it was instant on refresh.
